### ISSUE TITLE
KendoNumericTextBox: not able to set value

### ISSUE THREAD

**Issue by SivaATF** [atata-framework/atata-kendoui#40] opened 2019-11-06 23:52 UTC
I'm trying to set the value for kendo numeric text box and getting the below error.

I was able to set the value successfully when i change to Text Input and FindById.

  OpenQA.Selenium.NoSuchElementException : Unable to locate visible element:
    - By.XPath: .//*[normalize-space(@id) = 'TextId']/descendant-or-self::*[contains(concat(' ', normalize-space(@class), ' '), ' k-numerictextbox ')]

Using Kendo UI MVC  version -  2018.1.117.

Thanks.

**Comment by YevgeniyShunevych** [comment] 2019-11-08 14:48
Could you please share the HTML block of your `k-widget k-numerictextbox` with contents and probably related `<label>` element? Also which `FindAttribute` do you use, `FindById` or `FindByLabel` (default one)?

**Comment by SivaATF** [comment] 2019-11-08 15:11
Initially i didn't have any Find attribute and the framework used FindByLabel attribute.

Later i was able to find the Kendo Numeric Text Box using FindByXPath attribute. I think this was the same issue when i initially worked on Kendo dropdown. We need to either use FindByXPath or FindByIndex. There are 2 or 3 numeric text box in that page.

`<span class="k-widget k-numerictextbox focus" style=""><span class="k-numeric-wrap k-state-default k-expand-padding"><input type="text" class="k-formatted-value focus k-input k-valid" title="" tabindex="0" role="spinbutton" aria-disabled="false" style="display: inline-block;"><input class="focus k-input k-valid" data-val="true" data-val-number="The field Text Id must be a number." id="TextId" name="TextId" type="text" data-role="numerictextbox" role="spinbutton" style="display: none;" aria-disabled="false"><span class="k-icon k-i-warning" style="display: none;"></span><span class="k-select" style="display: none;"><span unselectable="on" class="k-link k-link-increase" aria-label="Increase value" title="Increase value"><span unselectable="on" class="k-icon k-i-arrow-60-up"></span></span><span unselectable="on" class="k-link k-link-decrease" aria-label="Decrease value" title="Decrease value"><span unselectable="on" class="k-icon k-i-arrow-60-down"></span></span></span></span></span>`

**Comment by YevgeniyShunevych** [comment] 2019-11-08 16:40
HTML for this control looks typical and valid for `KendoNumericTextBox`. But XPath that is in your exception should be different.

Could you please provide a stack trace of this exception:

> OpenQA.Selenium.NoSuchElementException : Unable to locate visible element:
> - By.XPath: .//[normalize-space(@id) = 'TextId']/descendant-or-self::[contains(concat(' ', normalize-space(@Class), ' '), ' k-numerictextbox ')]

Also please mention the version of Atata and Atata.KendoUI packages.

**Comment by SivaATF** [comment] 2019-11-08 17:30
As i mentioned earlier, i was able to proceed for now using FindByIndex and FindByXPath.

Thanks for your support and guidance.

Here is the full exception
 
OpenQA.Selenium.NoSuchElementException : Unable to locate visible element:
    - By.XPath: .//*[normalize-space(@id) = 'TextId']/descendant-or-self::*[contains(concat(' ', normalize-space(@class), ' '), ' k-numerictextbox ')]
    - Search time: 5.009s
    - Search options: {Visibility=Visible, Timeout=5s, RetryInterval=0.5s, IsSafely=False}
    
    Context element:
    - Tag: body
    - Location: {X=0, Y=0}
    - Size: {Width=779, Height=1159}
    - Element ID: 24513240-93d1-4f85-bf82-121c5b795c41
    - Text:

**Comment by YevgeniyShunevych** [comment] 2019-11-11 16:44
Thanks, but please share the stack trace of the exception, like below:

```
   at Atata.ExtendedSearchContext`1.Find(By by)
   at Atata.ExtendedSearchContext`1.FindElement(By by)
   at Atata.FindByLabelStrategy.Find(IWebElement scope, ComponentScopeLocateOptions options, SearchOptions searchOptions)
   at Atata.StrategyScopeLocator.GetScopeLocateResults(SearchOptions searchOptions)
   at Atata.StrategyScopeLocator.GetElement(SearchOptions searchOptions, String xPathCondition)
   at Atata.UIComponent`1.OnGetScopeElement(SearchOptions searchOptions)
   at Atata.UIComponent.GetScopeElement(SearchOptions searchOptions)
   at Atata.UIComponent.get_Scope()
   at Atata.KendoUI.KendoNumericTextBox`2.SetValue(T value) in C:\Development\atata-kendoui\src\Atata.KendoUI\KendoNumericTextBox`2.cs:line 28
   at Atata.EditableField`2.Set(T value)
   at Atata.KendoUI.Tests.KendoNumericTextBoxTests.KendoNumericTextBox() in C:\Development\atata-kendoui\src\Atata.KendoUI.Tests\KendoNumericTextBoxTests.cs:line 22
```

It should be displayed in Visual Studio Test Explorer and be added to the log file.

Also please mention the version of Atata and Atata.KendoUI packages.

**Comment by SivaATF** [comment] 2019-11-12 18:46
Here you go. I'm not using the nuget packages. I'm using the direct code version. My application uses only .NET Framework 4.5

at Atata.AssertionVerificationStrategy.ReportFailure(String message, Exception exception) in C:\POC\Atata\Atata\Atata\Verification\Strategies\AssertionVerificationStrategy.cs:line 25
   at Atata.VerificationProvider`2.Atata.IVerificationProvider<TOwner>.ReportFailure(String message, Exception exception) in C:\POC\Atata\Atata\Atata\Verification\VerificationProvider`2.cs:line 115
   at Atata.IUIComponentVerificationProviderExtensions.Exist[TComponent,TOwner](IUIComponentVerificationProvider`2 should) in C:\POC\Atata\Atata\Atata\Verification\IUIComponentVerificationProviderExtensions.cs:line 47
   at Atata.UI.Tests.PersonSearchTests.PersonSearch() in C:\POC\Atata\Atata.UI.Tests\Atata.UI.Tests\PersonSearchTests.cs:line 19
--NoSuchElementException
   at Atata.ExtendedSearchContext`1.Find(By by) in C:\POC\Atata\Atata.WebDriverExtras\Atata.WebDriverExtras\SearchContexts\ExtendedSearchContext`1.cs:line 170
   at Atata.ExtendedSearchContext`1.FindElement(By by) in C:\POC\Atata\Atata.WebDriverExtras\Atata.WebDriverExtras\SearchContexts\ExtendedSearchContext`1.cs:line 54
   at Atata.ISearchContextExtensions.Get[T](T searchContext, By by) in C:\POC\Atata\Atata.WebDriverExtras\Atata.WebDriverExtras\Extensions\ISearchContextExtensions.cs:line 12
   at Atata.XPathComponentScopeLocateResult.Get(String xPathCondition) in C:\POC\Atata\Atata\Atata\ScopeSearch\XPathComponentScopeLocateResult.cs:line 23
   at Atata.StrategyScopeLocator.<>c__DisplayClass4_0.<GetElement>b__0(XPathComponentScopeLocateResult x) in C:\POC\Atata\Atata\Atata\ScopeSearch\StrategyScopeLocator.cs:line 28
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Atata.StrategyScopeLocator.GetElement(SearchOptions searchOptions, String xPathCondition) in C:\POC\Atata\Atata\Atata\ScopeSearch\StrategyScopeLocator.cs:line 28
   at Atata.UIComponent`1.OnGetScopeElement(SearchOptions searchOptions) in C:\POC\Atata\Atata\Atata\Components\UIComponent`1.cs:line 135
   at Atata.UIComponent.GetScopeElement(SearchOptions searchOptions) in C:\POC\Atata\Atata\Atata\Components\UIComponent.cs:line 106
   at Atata.UIComponent.Exists(SearchOptions options) in C:\POC\Atata\Atata\Atata\Components\UIComponent.cs:line 160
   at Atata.IUIComponentVerificationProviderExtensions.<>c__DisplayClass0_0`2.<Exist>b__0(SearchOptions options) in C:\POC\Atata\Atata\Atata\Verification\IUIComponentVerificationProviderExtensions.cs:line 35
   at Atata.StaleSafely.Execute(Action`1 action, SearchOptions options) in C:\POC\Atata\Atata.WebDriverExtras\Atata.WebDriverExtras\StaleSafely.cs:line 99
   at Atata.IUIComponentVerificationProviderExtensions.Exist[TComponent,TOwner](IUIComponentVerificationProvider`2 should) in C:\POC\Atata\Atata\Atata\Verification\IUIComponentVerificationProviderExtensions.cs:line 29

**Comment by YevgeniyShunevych** [comment] 2019-11-13 17:20
Thanks. I see some unusual things in the stack trace. Could you please also show how this control is defined in the page object? Just copy the failing property with its attributes, please.

**Comment by SivaATF** [comment] 2019-11-14 19:43
Please find the property.

        [FindById("TextId")] //FindById not working for Kendo control. Please use FindByIndex or FindByXPath
        //[FindByXPath(AbpIdXPath)]
        //[FindByIndex(1)]
        public KendoNumericTextBox<_> TextId { get; private set; }

**Comment by YevgeniyShunevych** [comment] 2019-11-15 15:43
OK. I thought that you have an issue using `FindByLabel` which is the default search. If the issue is in `FindById`, then yes, it will not find `KendoNumericTextBox` as `id` is located in the descendant `input` element of `.k-numerictextbox`. `FindById` looks for an element with `id` and then searches for descendant or self matching control definition, which is opposite. If you want to find it by that `id` then you can try to use new `FindByDescendantIdAttribute` that I [added today](https://github.com/atata-framework/atata/issues/329):

```cs
[FindByDescendantId("TextId")]
public KendoNumericTextBox<_> TextId { get; private set; }
```

**Comment by SivaATF** [comment] 2019-11-27 21:20
After using the FindByDescendantIdAttribute, its able to find the element but not able to set any value.

2019-11-27 16:18:19.8962 ERROR OpenQA.Selenium.Atata : element not interactable
  (Session info: chrome=78.0.3904.108)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.SendKeys(String text)
   at Atata.IWebElementExtensions.FillInWith(IWebElement element, String text) in C:\POC\Atata\Atata.WebDriverExtras\Atata.WebDriverExtras\Extensions\IWebElementExtensions.cs:line 42
   at Atata.Input`2.SetValue(T value) in C:\POC\Atata\Atata\Atata\Components\Fields\Input`2.cs:line 25
   at Atata.EditableField`2.Set(T value) in C:\POC\Atata\Atata\Atata\Components\Fields\EditableField`2.cs:line 63
   at Atata.KendoUI.KendoNumericTextBox`2.SetValue(T value) in C:\POC\Atata\Atata.KendoUI\Atata.KendoUI\KendoNumericTextBox`2.cs:line 34
   at Atata.EditableField`2.Set(T value) in C:\POC\Atata\Atata\Atata\Components\Fields\EditableField`2.cs:line 63

**Comment by YevgeniyShunevych** [comment] 2019-11-28 16:41
I was able to reproduce your error for Vue and Angular versions of Kendo UI NumericTextBox. Trying to implement a fix.

**Comment by YevgeniyShunevych** [comment] 2019-11-29 14:03
I've implemented and committed a fix. @SivaATF please verify it.

**Comment by SivaATF** [comment] 2019-11-30 14:07
Should this fix need to be implemented in other Kendo control. I might be using the KendoDropdown.

**Comment by SivaATF** [comment] 2019-12-01 10:43
The fix worked. Now able to set the value. Thank you.

**Closed** 2019-12-05 10:36 UTC
Labels: bug
